FROM php:8.2-fpm AS shared_base
WORKDIR /var/www/html
RUN apt-get update && apt-get upgrade -y && apt-get install -y libpq-dev sendmail
RUN docker-php-ext-install pdo pdo_pgsql pgsql

FROM shared_base AS builder
WORKDIR /var/www/html
RUN apt-get install -y \
    unzip \
    git \
    libzip-dev \
    libpq-dev \
    libcurl4-openssl-dev
RUN docker-php-ext-install zip pdo pdo_pgsql pgsql curl
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer require smarty/smarty
RUN composer require phpunit/phpunit

FROM shared_base AS runtime
WORKDIR /var/www/html
COPY --chown=www-data:www-data --chmod=775 ./html/ /var/www/html/
COPY --from=builder --chown=www-data:www-data --chmod=775 /var/www/html/vendor/ /var/www/html/vendor/
EXPOSE 9000
CMD ["php", "-S", "0.0.0.0:9000"]
