# Use the official PHP image with Apache
FROM php:8.2-apache

# Set the working directory to /var/www/html
WORKDIR /var/www/html

# Install dependencies (unzip, git, PostgreSQL extensions, etc.) and Composer
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    unzip \
    git \
    libzip-dev \
    libpq-dev \
    && docker-php-ext-install zip pdo pdo_pgsql pgsql \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Smarty using Composer
RUN composer require smarty/smarty

COPY ./etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf

# Enable the SSL VirtualHost and default site
RUN a2enmod rewrite ssl && a2ensite 000-default.conf

# Expose HTTPS
EXPOSE 443

# Copy application code into /var/www/html and set permissions
COPY --chown=www-data:www-data --chmod=775 ./Code/ /var/www/html/

# Set the entrypoint to run Apache in the foreground
CMD ["apache2-foreground"]
