services:
  php:
    env_file: [ .env ]
    image: php:8.2-fpm
    user: www-data:www-data
    volumes:
      - ./Code:/var/www/html:rw
    restart: unless-stopped

  nginx:
    depends_on:
      - php
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl/certs/rr-origin.pem:/etc/ssl/certs/rr-origin.pem
      - ./etc/ssl/private/rr-private-key.pem:/etc/ssl/private/rr-private-key.pem
    restart: unless-stopped