apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: {{ .Values.php.image }}
          volumeMounts:
            - name: code-volume
              mountPath: /var/www/html
          envFrom:
            - configMapRef:
                name: php-env-config
          securityContext:
            runAsUser: 33
            runAsGroup: 33

