FROM php:8.2-apache AS builder
WORKDIR /var/www/html

# update base system
RUN apt-get update && apt-get upgrade -y

# install runtime dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
libpq-dev \
sendmail \
libcurl4-openssl-dev
RUN docker-php-ext-install pdo pdo_pgsql pgsql

# install build dependencies
RUN apt-get install -y \
    unzip \
    git \
    libzip-dev \
    libpq-dev \
    libcurl4-openssl-dev \
    nginx \
    && docker-php-ext-install zip pdo pdo_pgsql pgsql curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# use Composer for dependency management
RUN composer require smarty/smarty
RUN composer require phpunit/phpunit

# Copy Apache configuration
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf

# Enable Apache modules and site
RUN a2enmod rewrite ssl && a2ensite 000-default.conf

FROM php:8.2-apache AS runtime
WORKDIR /var/www/html
EXPOSE 80
COPY --chown=www-data:www-data --chmod=775 ./html/ /var/www/html/
COPY --from=builder --chown=www-data:www-data --chmod=775 /var/www/html/vendor/ /var/www/html/vendor/
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite ssl && a2ensite 000-default.conf
CMD ["apache2-foreground"]
