services:
  php:
    env_file: [ .env ]
    image: ghcr.io/wilsonify/c15-credit-card-transactions-authorize-net:latest
    user: www-data:www-data
    ports: [ "8080:80" ]
    restart: unless-stopped
