services:
  php:
    env_file: [ .env ]
    image: ghcr.io/wilsonify/c13-implementing-the-order-pipeline-part-i:latest
    user: www-data:www-data
    ports: [ "8080:80" ]
    restart: unless-stopped
