FROM php:8.2-fpm
WORKDIR /var/www/html
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    unzip \
    git \
    libzip-dev \
    libpq-dev \
    && docker-php-ext-install zip pdo pdo_pgsql pgsql \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer require smarty/smarty
RUN composer require phpunit/phpunit
CMD ["php-fpm", "--nodaemonize"]
