services:
  php:
    env_file: [ .env ]
    image: ghcr.io/wilsonify/c01-base-image:latest
    restart: unless-stopped
    volumes:
      - ./ssl/certs/rr-origin.pem:/etc/ssl/certs/rr-origin.pem
      - ./ssl/private/rr-private-key.pem:/etc/ssl/private/rr-private-key.pem
    ports:
      - "444:443"

  nginx:
    env_file: [ .env ]
    image: ghcr.io/wilsonify/c00-nginx-image:latest
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./ssl/certs/rr-origin.pem:/etc/ssl/certs/rr-origin.pem
      - ./ssl/private/rr-private-key.pem:/etc/ssl/private/rr-private-key.pem
