FROM php:8.2-apache AS builder

# Set working directory
WORKDIR /var/www/html

# dependency management with Composer
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    libcurl4-openssl-dev \
    libpq-dev \
    libzip-dev \
    sendmail \
    unzip \
    zip && \
    docker-php-ext-install \
    zip \
    pdo \
    pdo_pgsql \
    pgsql \
    curl && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer --version

RUN composer require smarty/smarty
RUN composer require phpunit/phpunit

# Copy Apache configuration
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf

# Enable Apache modules and site
RUN a2enmod rewrite ssl && a2ensite 000-default.conf

FROM php:8.2-apache AS runtime
WORKDIR /var/www/html
EXPOSE 443
COPY --chown=www-data:www-data --chmod=775 ./html/ /var/www/html/
COPY --from=builder --chown=www-data:www-data --chmod=775 /var/www/html/vendor/ /var/www/html/vendor/
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite ssl && a2ensite 000-default.conf
CMD ["apache2-foreground"]
