FROM php:8.2-apache

# Set working directory
WORKDIR /var/www/html

# dependency management with Composer
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    libcurl4-openssl-dev \
    libpq-dev \
    libzip-dev \
    sendmail \
    unzip \
    zip && \
    docker-php-ext-install \
    zip \
    pdo \
    pdo_pgsql \
    pgsql \
    curl && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer --version

RUN composer require smarty/smarty
RUN composer require phpunit/phpunit

# Copy Apache configuration
COPY ./etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf

# Enable Apache modules and site
RUN a2enmod rewrite ssl && a2ensite 000-default.conf

# Expose port
EXPOSE 443

# Copy application code
COPY --chown=www-data:www-data --chmod=775 ./var/www/html/index.php /var/www/html/index.php
COPY --chown=www-data:www-data --chmod=775 ./var/www/html/hatshop.css /var/www/html/hatshop.css
COPY --chown=www-data:www-data --chmod=775 ./var/www/html/business/ /var/www/html/business/
COPY --chown=www-data:www-data --chmod=775 ./var/www/html/include/ /var/www/html/include/
COPY --chown=www-data:www-data --chmod=775 ./var/www/html/presentation/ /var/www/html/presentation/

# Run Apache
CMD ["apache2-foreground"]
