FROM php:8.2-apache

# Set working directory
WORKDIR /var/www/html

# Install dependencies and Composer
RUN apt-get update && \
    apt-get install -y --no-install-recommends zip unzip git && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer --version

# Require Smarty
RUN composer require smarty/smarty

# Copy Apache configuration
COPY ./etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf

# Enable Apache modules and site
RUN a2enmod rewrite ssl && a2ensite 000-default.conf

# Expose port
EXPOSE 443

# Copy application code
COPY --chown=www-data:www-data --chmod=775 ./Code/ /var/www/html/

# Run Apache
CMD ["apache2-foreground"]
