services:

  nginx:
    environment: [ "NGINX_SERVER=localhost" ]
    image: ghcr.io/wilsonify/c00-nginx-image:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
