FROM php:8.2-apache AS shared_base
WORKDIR /var/www/html

# update base system
RUN apt-get update && apt-get upgrade -y

# Install necessary dependencies
RUN apt-get update && apt-get install -y  \
    git \
    libc-client-dev \
    libcurl3-dev \
    libcurl4-openssl-dev \
    libfreetype6-dev \
    libicu-dev \
    libjpeg62-turbo-dev \
    libkrb5-dev \
    libmcrypt-dev \
    libmemcached-dev \
    libonig-dev \
    libpng-dev \
    libpq-dev \
    libxml2-dev \
    libzip-dev \
    unzip \
    zlib1g-dev


# PHP extensions
RUN docker-php-ext-install -j$(nproc) bcmath
RUN docker-php-ext-install -j$(nproc) curl
RUN docker-php-ext-install -j$(nproc) iconv
RUN docker-php-ext-install -j$(nproc) intl
RUN docker-php-ext-install -j$(nproc) mbstring
RUN docker-php-ext-install -j$(nproc) pdo
RUN docker-php-ext-install -j$(nproc) pdo_pgsql
RUN docker-php-ext-install -j$(nproc) pgsql
RUN docker-php-ext-install -j$(nproc) soap
RUN docker-php-ext-install -j$(nproc) xml
RUN docker-php-ext-install -j$(nproc) zip

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# use Composer for dependency management
COPY --chown=www-data:www-data --chmod=775 ./html/ /var/www/html/
RUN composer install
RUN chown -R www-data:www-data /var/www/html/vendor/

# Enable Apache modules and site
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite && a2ensite 000-default.conf
EXPOSE 80
USER www-data
CMD ["apache2-foreground"]
